development: 
  # adapter: sqlite3
  # database: postgres
  # password: 191192
  # pool: 5
  # timeout: 5000
  # username: postgres
production: 
  # adapter: sqlite3
  # database: postgres
  # pool: 5
  # timeout: 5000
test: 
  # adapter: sqlite3
  # database: postgres
  # pool: 5
  # timeout: 5000